name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
  
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install flake8 black
      - name: Linting
        run: flake8 calculator.py test_calculator.py
      - name: Formatting
        run: black --check calculator.py test_calculator.py

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pytest
      - run: pytest